### ISSUE TITLE
sqlite3.InterfaceError: Error binding parameter 1 - probably unsupported type.

### ISSUE THREAD

**Issue by zam89** [guelfoweb/peframe#3]
Hi,
today I tried to play around with this tool with some of my samples.

But I noticed that some of my sample with show this kind of error if the sample is analyse for the first time. If I run the same command with the same sample, then the error will gone.

This is the error looks like:

```
$ python peframe.py ../binaries/PE32/small/de85ae919d48325189bead995e8052e7

Short information
------------------------------------------------------------
File Name          de85ae919d48325189bead995e8052e7
File Size          44420 byte
Compile Time       2009-03-28 01:32:04
DLL                No
Sections           3
Hash MD5           de85ae919d48325189bead995e8052e7
Hash SAH1          0f1892137e3a42997eaf21bef7540616c9d5fbc3
Imphash            b48d4f95b75d3b29bfe6a5d6b20bb1d0
Packer             Yes
Anti Debug         Yes
Anti VM            No
Directory          Import

Packer matched [5]
------------------------------------------------------------
Packer             Microsoft Visual C++ v6.0
Packer             Microsoft Visual C++ 5.0
Packer             Microsoft Visual C++
Packer             Microsoft Visual C++ v6.0
Packer             Installer VISE Custom

Anti Debug discovered [2]
------------------------------------------------------------
Function           TerminateProcess
Function           UnhandledExceptionFilter

Suspicious API discovered [28]
------------------------------------------------------------
Function           CopyFileA
Function           CreateProcessA
Function           CreateThread
Function           DeleteFileA
Function           ExitThread
Function           GetCommandLineA
Function           GetComputerNameA
Function           GetCurrentProcess
Function           GetModuleFileNameA
Function           GetModuleHandleA
Function           GetProcAddress
Function           GetStartupInfoA
Function           GetTickCount
Function           GetUserNameA
Function           LoadLibraryA
Function           RegCloseKey
Function           RegCreateKeyExA
Function           Sleep
Function           TerminateProcess
Function           UnhandledExceptionFilter
Function           VirtualAlloc
Function           VirtualFree
Function           WSAStartup
Function           WriteFile
Function           closesocket
Function           connect
Function           send
Function           socket

File name discovered [10]
------------------------------------------------------------
Executable         %s\admin$\system32\dnsapi.exe
Library            ADVAPI32.dll
Library            KERNEL32.dll
Library            MPR.dll
Library            NETAPI32.dll
Library            WS2_32.dll
Executable         \msupd.exe
Library            urlmon.dll
Library            user32.dll
Library            wininet.dll

Url discovered [1]
------------------------------------------------------------
Url                http://fukyu.jp/updata/ACCl3.jpg

Wait please... storing info into the db
Traceback (most recent call last):
  File "peframe.py", line 401, in <module>
    autoanalysis(filename)
  File "peframe.py", line 349, in autoanalysis
    au_show_sec,au_show_furl,au_show_meta)
  File "modules/db_manage.py", line 107, in dbmanage
    cur.execute('''INSERT INTO show_url (id, url) VALUES (?, ?)''', (idrif, au_show_furl[1][i]))
sqlite3.InterfaceError: Error binding parameter 1 - probably unsupported type.
```

This happen to some of my sample only and not all of it.
Is it normal? Or do I miss something? Thanks.

**Comment by Ameshsree** [comment]
sqlite3.InterfaceError: Error binding parameter 3 - probably unsupported type.
